use super::OptTask;

pub fn all_tasks() -> Vec<OptTask> {
    vec![
        OptTask {
            id: "dns_flush".into(),
            name: "Flush DNS Cache".into(),
            description: "Clear the DNS resolver cache to fix stale lookups".into(),
            command: "dscacheutil -flushcache".into(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "cache_refresh".into(),
            name: "Refresh QuickLook Cache".into(),
            description: "Reset QuickLook thumbnail and preview caches".into(),
            command: "qlmanage -r cache 2>/dev/null".into(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "saved_state".into(),
            name: "Clean Saved Application State".into(),
            description: "Remove old saved window state data from apps".into(),
            command: "rm -rf ~/Library/Saved\\ Application\\ State/*".into(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "launch_services".into(),
            name: "Rebuild LaunchServices".into(),
            description: "Fix broken 'Open with' menus and file associations".into(),
            command: "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user 2>/dev/null".into(),
            needs_admin: false,
            warning: Some("Finder may restart briefly".into()),
        },
        OptTask {
            id: "icon_cache".into(),
            name: "Refresh Icon Cache".into(),
            description: "Clear cached app icons to fix display issues".into(),
            command: "sudo rm -rfv /Library/Caches/com.apple.iconservices.store 2>/dev/null; sudo find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {} + 2>/dev/null; killall Dock 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("Dock will restart".into()),
        },
        OptTask {
            id: "sqlite_vacuum".into(),
            name: "Vacuum SQLite Databases".into(),
            description: "Compact Mail, Messages, and Safari databases to free space".into(),
            command: "find ~/Library/Mail ~/Library/Messages ~/Library/Safari -name '*.db' -size -100M -exec sqlite3 {} 'VACUUM;' \\; 2>/dev/null".into(),
            needs_admin: false,
            warning: Some("Close Mail, Messages, Safari first".into()),
        },
        OptTask {
            id: "font_cache".into(),
            name: "Rebuild Font Cache".into(),
            description: "Rebuild system font cache to fix rendering issues".into(),
            command: "sudo atsutil databases -remove 2>/dev/null; atsutil server -shutdown 2>/dev/null; atsutil server -ping 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("Close browsers before running".into()),
        },
        OptTask {
            id: "memory_purge".into(),
            name: "Purge Inactive Memory".into(),
            description: "Release inactive memory back to the system".into(),
            command: "sudo purge".into(),
            needs_admin: true,
            warning: Some("Brief performance dip while memory is reorganized".into()),
        },
        OptTask {
            id: "network_flush".into(),
            name: "Flush Network Stack".into(),
            description: "Clear routing table and ARP cache to fix connectivity".into(),
            command: "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder 2>/dev/null".into(),
            needs_admin: true,
            warning: None,
        },
        OptTask {
            id: "disk_permissions".into(),
            name: "Repair Disk Permissions".into(),
            description: "Reset user home directory permissions to defaults".into(),
            command: "diskutil resetUserPermissions / $(id -u) 2>/dev/null".into(),
            needs_admin: false,
            warning: Some("May take a minute".into()),
        },
        OptTask {
            id: "bluetooth_reset".into(),
            name: "Reset Bluetooth Module".into(),
            description: "Restart the Bluetooth daemon to fix connection issues".into(),
            command: "sudo pkill bluetoothd 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("Bluetooth devices will reconnect automatically".into()),
        },
        OptTask {
            id: "spotlight_rebuild".into(),
            name: "Rebuild Spotlight Index".into(),
            description: "Re-index the entire disk for faster search results".into(),
            command: "sudo mdutil -E / 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("Takes 1-2 hours; connect to power first".into()),
        },
        OptTask {
            id: "dock_refresh".into(),
            name: "Refresh Dock Cache".into(),
            description: "Reset the Dock to fix stuck or missing icons".into(),
            command: "defaults delete com.apple.dock; killall Dock 2>/dev/null".into(),
            needs_admin: false,
            warning: Some("Dock will restart and reset to defaults".into()),
        },
        OptTask {
            id: "firewall_enable".into(),
            name: "Enable Firewall".into(),
            description: "Turn on the macOS application firewall for security".into(),
            command: "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on 2>/dev/null".into(),
            needs_admin: true,
            warning: None,
        },
    ]
}
