use super::OptTask;

pub fn all_tasks() -> Vec<OptTask> {
    vec![
        OptTask {
            id: "dns_flush".into(),
            name: "Flush DNS Cache".into(),
            description: "Clear the DNS resolver cache to fix stale lookups".into(),
            command: "dscacheutil -flushcache".into(),
            needs_admin: true,
            warning: None,
        },
        OptTask {
            id: "cache_refresh".into(),
            name: "Refresh QuickLook Cache".into(),
            description: "Reset QuickLook thumbnail and preview caches".into(),
            // Command unused — custom runner handles this task
            command: String::new(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "saved_state".into(),
            name: "Clean Saved Application State".into(),
            description: "Remove saved window state older than 30 days".into(),
            // Command unused — custom runner handles this task
            command: String::new(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "launch_services".into(),
            name: "Rebuild LaunchServices".into(),
            description: "Fix broken 'Open with' menus and file associations".into(),
            command: "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -gc 2>/dev/null; /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -r -f -domain local -domain user -domain system 2>/dev/null".into(),
            needs_admin: false,
            warning: Some("Finder may restart briefly".into()),
        },
        OptTask {
            id: "icon_cache".into(),
            name: "Refresh Icon Cache".into(),
            description: "Clear cached app icons to fix display issues".into(),
            command: "rm -rfv /Library/Caches/com.apple.iconservices.store 2>/dev/null; find /private/var/folders/ -maxdepth 5 -name com.apple.iconservices -exec rm -rf {} + 2>/dev/null; killall Dock 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("Dock will restart briefly".into()),
        },
        OptTask {
            id: "sqlite_vacuum".into(),
            name: "Vacuum SQLite Databases".into(),
            description: "Compact Mail, Messages, and Safari databases to free space".into(),
            // Command is unused — custom runner handles this task
            command: String::new(),
            needs_admin: false,
            warning: Some("Mail, Messages, and Safari must be closed".into()),
        },
        OptTask {
            id: "plist_repair".into(),
            name: "Repair Broken Preferences".into(),
            description: "Validates preference files and removes corrupted ones".into(),
            // Command is unused — custom runner handles this task
            command: String::new(),
            needs_admin: false,
            warning: Some("Corrupted preference files will be removed; apps will recreate them".into()),
        },
        OptTask {
            id: "font_cache".into(),
            name: "Rebuild Font Cache".into(),
            description: "Rebuild system font cache to fix rendering issues".into(),
            command: "atsutil databases -remove 2>/dev/null; atsutil server -shutdown 2>/dev/null; atsutil server -ping 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("Close browsers before running".into()),
        },
        OptTask {
            id: "memory_purge".into(),
            name: "Purge Inactive Memory".into(),
            description: "Release inactive memory back to the system".into(),
            command: "purge".into(),
            needs_admin: true,
            warning: Some("Brief performance dip while memory is reorganized".into()),
        },
        OptTask {
            id: "network_flush".into(),
            name: "Flush Network Stack".into(),
            description: "Clear routing table and ARP cache to fix connectivity".into(),
            command: "dscacheutil -flushcache; killall -HUP mDNSResponder 2>/dev/null; route -n flush 2>/dev/null; arp -a -d 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("May briefly interrupt network connections".into()),
        },
        OptTask {
            id: "disk_permissions".into(),
            name: "Repair Disk Permissions".into(),
            description: "Reset user home directory permissions to defaults".into(),
            command: "diskutil resetUserPermissions / $(id -u) 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("May take a minute".into()),
        },
        OptTask {
            id: "bluetooth_reset".into(),
            name: "Reset Bluetooth Module".into(),
            description: "Restart the Bluetooth daemon to fix connection issues".into(),
            // Command unused — custom runner handles SIGKILL escalation
            command: String::new(),
            needs_admin: true,
            warning: Some("Bluetooth devices will reconnect automatically".into()),
        },
        OptTask {
            id: "spotlight_rebuild".into(),
            name: "Rebuild Spotlight Index".into(),
            description: "Re-index the entire disk for faster search results".into(),
            command: "mdutil -E / 2>/dev/null".into(),
            needs_admin: true,
            warning: Some("Takes 1-2 hours; connect to power first".into()),
        },
        OptTask {
            id: "dock_refresh".into(),
            name: "Refresh Dock Cache".into(),
            description: "Clear stale Dock database files to fix stuck or missing icons".into(),
            command: "find ~/Library/Application\\ Support/Dock -name '*.db' -delete 2>/dev/null; touch ~/Library/Preferences/com.apple.dock.plist 2>/dev/null; killall Dock 2>/dev/null".into(),
            needs_admin: false,
            warning: Some("Dock will restart briefly".into()),
        },
        OptTask {
            id: "firewall_enable".into(),
            name: "Enable Firewall".into(),
            description: "Turn on the macOS application firewall for security".into(),
            command: "/usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on 2>/dev/null".into(),
            needs_admin: true,
            warning: None,
        },
        OptTask {
            id: "quarantine_cleanup".into(),
            name: "Clear Quarantine History".into(),
            description: "Remove Gatekeeper download tracking records".into(),
            command: String::new(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "prevent_network_dsstore".into(),
            name: "Prevent Network .DS_Store".into(),
            description: "Stop creating .DS_Store files on network and USB volumes".into(),
            command: "defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true; defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true".into(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "launch_agents_cleanup".into(),
            name: "Clean Stale Launch Agents".into(),
            description: "Remove user LaunchAgent plists that reference missing binaries".into(),
            command: String::new(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "periodic_maintenance".into(),
            name: "Run Periodic Maintenance".into(),
            description: "Execute macOS daily, weekly, and monthly maintenance scripts if overdue".into(),
            command: "periodic daily weekly monthly".into(),
            needs_admin: true,
            warning: Some("May take a few minutes".into()),
        },
        OptTask {
            id: "shared_file_list_repair".into(),
            name: "Repair Shared File Lists".into(),
            description: "Reset corrupted Finder sidebar favorites and recent documents".into(),
            command: String::new(),
            needs_admin: false,
            warning: Some("Finder sidebar will reset to defaults".into()),
        },
        OptTask {
            id: "notification_cleanup".into(),
            name: "Clean Old Notifications".into(),
            description: "Remove notification records older than 30 days".into(),
            command: String::new(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "disk_verify".into(),
            name: "Verify Disk Health".into(),
            description: "Run filesystem integrity check on the boot volume".into(),
            command: "diskutil verifyVolume / 2>&1".into(),
            needs_admin: false,
            warning: Some("Read-only check, no changes are made".into()),
        },
        OptTask {
            id: "coreduet_cleanup".into(),
            name: "Clean Usage History".into(),
            description: "Trim old app usage records from the Knowledge database".into(),
            command: String::new(),
            needs_admin: false,
            warning: None,
        },
        OptTask {
            id: "login_items_audit".into(),
            name: "Audit Login Items".into(),
            description: "Detect broken login items that reference missing applications".into(),
            command: String::new(),
            needs_admin: false,
            warning: None,
        },
    ]
}
