use super::CleanRule;

pub fn all_rules() -> Vec<CleanRule> {
    vec![
        // ── System ──────────────────────────────────────────
        CleanRule {
            id: "system_caches".into(),
            max_age_days: None,
            category: "System".into(),
            label: "System Caches".into(),
            paths: vec!["/Library/Caches".into()],
        },
        CleanRule {
            id: "system_tmp".into(),
            max_age_days: Some(7),
            category: "System".into(),
            label: "Temporary Files".into(),
            paths: vec!["/private/tmp".into(), "/private/var/tmp".into()],
        },
        CleanRule {
            id: "system_logs".into(),
            max_age_days: Some(7),
            category: "System".into(),
            label: "System Logs".into(),
            paths: vec!["/private/var/log".into()],
        },
        CleanRule {
            id: "crash_reports".into(),
            max_age_days: Some(7),
            category: "System".into(),
            label: "Crash Reports".into(),
            paths: vec![
                "~/Library/Logs/DiagnosticReports".into(),
                "/Library/Logs/DiagnosticReports".into(),
            ],
        },
        CleanRule {
            id: "system_recent_items".into(),
            max_age_days: None,
            category: "System".into(),
            label: "Recent Items".into(),
            paths: vec![
                "~/Library/Application Support/com.apple.sharedfilelist".into(),
            ],
        },
        CleanRule {
            id: "system_mail_downloads".into(),
            max_age_days: Some(30),
            category: "System".into(),
            label: "Mail Downloads".into(),
            paths: vec!["~/Library/Mail Downloads".into()],
        },
        CleanRule {
            id: "system_diagnostic_logs".into(),
            max_age_days: Some(30),
            category: "System".into(),
            label: "Diagnostic Logs".into(),
            paths: vec!["/private/var/db/diagnostics".into()],
        },
        CleanRule {
            id: "system_power_logs".into(),
            max_age_days: Some(30),
            category: "System".into(),
            label: "Power Logs".into(),
            paths: vec!["/private/var/db/powerlog".into()],
        },
        CleanRule {
            id: "system_memory_exceptions".into(),
            max_age_days: Some(30),
            category: "System".into(),
            label: "Memory Exception Reports".into(),
            paths: vec!["/private/var/db/reportmemoryexception".into()],
        },
        CleanRule {
            id: "system_adobe_logs".into(),
            max_age_days: Some(7),
            category: "System".into(),
            label: "Adobe System Logs".into(),
            paths: vec![
                "/Library/Logs/Adobe".into(),
                "/Library/Logs/CreativeCloud".into(),
                "/Library/Logs/adobegc.log".into(),
            ],
        },
        CleanRule {
            id: "system_macos_installers".into(),
            max_age_days: None,
            category: "System".into(),
            label: "Old macOS Installers".into(),
            paths: vec![
                "/Applications/Install macOS Sonoma.app".into(),
                "/Applications/Install macOS Ventura.app".into(),
                "/Applications/Install macOS Monterey.app".into(),
                "/Applications/Install macOS Big Sur.app".into(),
                "/Applications/Install macOS Catalina.app".into(),
            ],
        },
        // ── User ────────────────────────────────────────────
        CleanRule {
            id: "user_caches".into(),
            max_age_days: None,
            category: "User".into(),
            label: "User Caches".into(),
            paths: vec!["~/Library/Caches".into()],
        },
        CleanRule {
            id: "user_logs".into(),
            max_age_days: None,
            category: "User".into(),
            label: "User Logs".into(),
            paths: vec!["~/Library/Logs".into()],
        },
        CleanRule {
            id: "trash".into(),
            max_age_days: None,
            category: "User".into(),
            label: "Trash".into(),
            paths: vec!["~/.Trash".into()],
        },
        // ── Browsers ────────────────────────────────────────
        CleanRule {
            id: "safari_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Safari Cache".into(),
            paths: vec![
                "~/Library/Caches/com.apple.Safari".into(),
                "~/Library/Caches/com.apple.Safari.SearchHelper".into(),
            ],
        },
        CleanRule {
            id: "chrome_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Chrome Cache".into(),
            paths: vec![
                "~/Library/Caches/Google/Chrome".into(),
                "~/Library/Application Support/Google/Chrome/Default/Cache".into(),
                "~/Library/Application Support/Google/Chrome/Default/Code Cache".into(),
                "~/Library/Application Support/Google/Chrome/Default/GPUCache".into(),
            ],
        },
        CleanRule {
            id: "firefox_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Firefox Cache".into(),
            paths: vec!["~/Library/Caches/Firefox".into()],
        },
        CleanRule {
            id: "edge_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Edge Cache".into(),
            paths: vec!["~/Library/Caches/Microsoft Edge".into()],
        },
        CleanRule {
            id: "brave_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Brave Cache".into(),
            paths: vec!["~/Library/Caches/BraveSoftware".into()],
        },
        CleanRule {
            id: "arc_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Arc Cache".into(),
            paths: vec!["~/Library/Caches/company.thebrowser.Browser".into()],
        },
        CleanRule {
            id: "opera_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Opera Cache".into(),
            paths: vec!["~/Library/Caches/com.operasoftware.Opera".into()],
        },
        CleanRule {
            id: "vivaldi_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Vivaldi Cache".into(),
            paths: vec!["~/Library/Caches/com.vivaldi.Vivaldi".into()],
        },
        CleanRule {
            id: "chromium_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Chromium Cache".into(),
            paths: vec!["~/Library/Caches/Chromium".into()],
        },
        CleanRule {
            id: "orion_cache".into(),
            max_age_days: None,
            category: "Browsers".into(),
            label: "Orion Cache".into(),
            paths: vec!["~/Library/Caches/com.nickvision.Orion".into()],
        },
        // ── Developer Tools ─────────────────────────────────
        CleanRule {
            id: "dev_npm_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "npm Cache".into(),
            paths: vec!["~/.npm/_cacache".into()],
        },
        CleanRule {
            id: "dev_npm_logs".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "npm Logs".into(),
            paths: vec!["~/.npm/_logs".into()],
        },
        CleanRule {
            id: "dev_npm_prebuilds".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "npm Prebuilds".into(),
            paths: vec!["~/.npm/_prebuilds".into()],
        },
        CleanRule {
            id: "dev_yarn_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Yarn Cache".into(),
            paths: vec!["~/Library/Caches/Yarn".into(), "~/.cache/yarn".into()],
        },
        CleanRule {
            id: "dev_pnpm_store".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "pnpm Store".into(),
            paths: vec![
                "~/Library/pnpm/store".into(),
                "~/.local/share/pnpm/store".into(),
            ],
        },
        CleanRule {
            id: "dev_bun_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Bun Cache".into(),
            paths: vec!["~/.bun/install/cache".into()],
        },
        CleanRule {
            id: "dev_node_gyp".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "node-gyp Cache".into(),
            paths: vec!["~/.cache/node-gyp".into(), "~/.node-gyp".into()],
        },
        CleanRule {
            id: "dev_electron_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Electron Cache".into(),
            paths: vec![
                "~/Library/Caches/electron".into(),
                "~/.cache/electron".into(),
            ],
        },
        CleanRule {
            id: "dev_typescript_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "TypeScript Build Cache".into(),
            paths: vec!["~/.cache/typescript".into()],
        },
        CleanRule {
            id: "dev_turbo_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Turbo Cache".into(),
            paths: vec![
                "~/.cache/turbo".into(),
                "~/Library/Caches/turbo".into(),
            ],
        },
        CleanRule {
            id: "dev_eslint_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "ESLint Cache".into(),
            paths: vec!["~/.cache/eslint".into()],
        },
        CleanRule {
            id: "dev_prettier_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Prettier Cache".into(),
            paths: vec!["~/.cache/prettier".into()],
        },
        CleanRule {
            id: "dev_cargo_registry".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Cargo Registry Cache".into(),
            paths: vec!["~/.cargo/registry/cache".into()],
        },
        CleanRule {
            id: "dev_cargo_git".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Cargo Git Checkouts".into(),
            paths: vec!["~/.cargo/git/checkouts".into()],
        },
        CleanRule {
            id: "dev_cargo_src".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Cargo Registry Sources".into(),
            paths: vec!["~/.cargo/registry/src".into()],
        },
        CleanRule {
            id: "dev_rustup_downloads".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Rustup Downloads".into(),
            paths: vec!["~/.rustup/downloads".into()],
        },
        CleanRule {
            id: "dev_pip_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "pip Cache".into(),
            paths: vec!["~/Library/Caches/pip".into(), "~/.cache/pip".into()],
        },
        CleanRule {
            id: "dev_pyenv_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "pyenv Cache".into(),
            paths: vec!["~/.pyenv/cache".into()],
        },
        CleanRule {
            id: "dev_poetry_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Poetry Cache".into(),
            paths: vec!["~/Library/Caches/pypoetry".into()],
        },
        CleanRule {
            id: "dev_ruff_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Ruff Cache".into(),
            paths: vec!["~/.cache/ruff".into()],
        },
        CleanRule {
            id: "dev_mypy_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "mypy Cache".into(),
            paths: vec!["~/.cache/mypy".into()],
        },
        CleanRule {
            id: "dev_jupyter_runtime".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Jupyter Runtime".into(),
            paths: vec!["~/Library/Jupyter/runtime".into()],
        },
        CleanRule {
            id: "dev_conda_packages".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Conda Packages".into(),
            paths: vec![
                "~/anaconda3/pkgs".into(),
                "~/miniconda3/pkgs".into(),
            ],
        },
        CleanRule {
            id: "dev_go_build".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Go Build Cache".into(),
            paths: vec!["~/Library/Caches/go-build".into()],
        },
        CleanRule {
            id: "dev_go_mod_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Go Module Cache".into(),
            paths: vec!["~/go/pkg/mod/cache".into()],
        },
        CleanRule {
            id: "dev_gradle_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Gradle Cache".into(),
            paths: vec!["~/.gradle/caches".into()],
        },
        CleanRule {
            id: "dev_maven_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Maven Cache".into(),
            paths: vec!["~/.m2/repository".into()],
        },
        CleanRule {
            id: "dev_cocoapods_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "CocoaPods Cache".into(),
            paths: vec!["~/Library/Caches/CocoaPods".into()],
        },
        CleanRule {
            id: "dev_xcode_derived".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Xcode DerivedData".into(),
            paths: vec!["~/Library/Developer/Xcode/DerivedData".into()],
        },
        CleanRule {
            id: "dev_xcode_archives".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Xcode Archives".into(),
            paths: vec!["~/Library/Developer/Xcode/Archives".into()],
        },
        // Xcode Device Support is handled by a special scan
        // (`scan_xcode_device_support`) that preserves the N most recent
        // versions — re-downloading ~2 GB of device symbols blocks debugging
        // of real hardware until it completes.
        CleanRule {
            id: "dev_xcode_simulators".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Xcode Simulator Caches".into(),
            paths: vec!["~/Library/Developer/CoreSimulator/Caches".into()],
        },
        CleanRule {
            id: "dev_xcode_docsets".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Xcode Documentation".into(),
            paths: vec![
                "~/Library/Developer/Shared/Documentation/DocSets".into(),
            ],
        },
        CleanRule {
            id: "dev_docker_buildx".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Docker BuildX Cache".into(),
            paths: vec!["~/.docker/buildx".into()],
        },
        CleanRule {
            id: "dev_kubernetes_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Kubernetes Cache".into(),
            paths: vec![
                "~/.kube/cache".into(),
                "~/.kube/http-cache".into(),
            ],
        },
        CleanRule {
            id: "dev_aws_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "AWS CLI Cache".into(),
            paths: vec!["~/.aws/cli/cache".into()],
        },
        CleanRule {
            id: "dev_gcloud_logs".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Google Cloud Logs".into(),
            paths: vec!["~/.config/gcloud/logs".into()],
        },
        CleanRule {
            id: "dev_azure_logs".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Azure CLI Logs".into(),
            paths: vec!["~/.azure/logs".into()],
        },
        CleanRule {
            id: "dev_android_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Android SDK Cache".into(),
            paths: vec!["~/.android/cache".into()],
        },
        CleanRule {
            id: "dev_flutter_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Flutter Pub Cache".into(),
            paths: vec!["~/.pub-cache".into()],
        },
        CleanRule {
            id: "dev_deno_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Deno Cache".into(),
            paths: vec!["~/Library/Caches/deno".into()],
        },
        CleanRule {
            id: "dev_composer_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Composer Cache (PHP)".into(),
            paths: vec!["~/.composer/cache".into()],
        },
        CleanRule {
            id: "dev_rubygems_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "Ruby Gems Cache".into(),
            paths: vec!["~/.gem/ruby".into()],
        },
        CleanRule {
            id: "dev_jetbrains_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "JetBrains IDE Caches".into(),
            paths: vec!["~/Library/Caches/JetBrains".into()],
        },
        CleanRule {
            id: "dev_vscode_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "VS Code Cache".into(),
            paths: vec![
                "~/Library/Caches/com.microsoft.VSCode".into(),
                "~/Library/Application Support/Code/Cache".into(),
                "~/Library/Application Support/Code/CachedData".into(),
                "~/Library/Application Support/Code/CachedExtensions".into(),
            ],
        },
        CleanRule {
            id: "dev_uv_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "uv Cache (Python)".into(),
            paths: vec!["~/.cache/uv".into()],
        },
        CleanRule {
            id: "dev_huggingface".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "HuggingFace Cache".into(),
            paths: vec!["~/.cache/huggingface".into()],
        },
        CleanRule {
            id: "dev_torch_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "PyTorch Cache".into(),
            paths: vec!["~/.cache/torch".into()],
        },
        CleanRule {
            id: "dev_tensorflow_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "TensorFlow Cache".into(),
            paths: vec!["~/.cache/tensorflow".into()],
        },
        CleanRule {
            id: "dev_wandb_cache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "W&B Cache".into(),
            paths: vec!["~/.cache/wandb".into()],
        },
        CleanRule {
            id: "dev_pre_commit".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "pre-commit Cache".into(),
            paths: vec!["~/.cache/pre-commit".into()],
        },
        CleanRule {
            id: "dev_sccache".into(),
            max_age_days: None,
            category: "Developer Tools".into(),
            label: "sccache Cache".into(),
            paths: vec!["~/.cache/sccache".into()],
        },
        // ── Communication ───────────────────────────────────
        CleanRule {
            id: "comm_discord".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "Discord Cache".into(),
            paths: vec![
                "~/Library/Application Support/discord/Cache".into(),
                "~/Library/Application Support/discord/Code Cache".into(),
                "~/Library/Application Support/discord/GPUCache".into(),
            ],
        },
        CleanRule {
            id: "comm_slack".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "Slack Cache".into(),
            paths: vec![
                "~/Library/Application Support/Slack/Cache".into(),
                "~/Library/Application Support/Slack/Code Cache".into(),
                "~/Library/Application Support/Slack/GPUCache".into(),
                "~/Library/Caches/com.tinyspeck.slackmacgap".into(),
            ],
        },
        CleanRule {
            id: "comm_zoom".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "Zoom Cache".into(),
            paths: vec!["~/Library/Caches/us.zoom.xos".into()],
        },
        CleanRule {
            id: "comm_teams".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "Teams Cache".into(),
            paths: vec![
                "~/Library/Caches/com.microsoft.teams2".into(),
                "~/Library/Application Support/Microsoft/Teams/Cache".into(),
            ],
        },
        CleanRule {
            id: "comm_telegram".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "Telegram Cache".into(),
            paths: vec![
                "~/Library/Caches/ru.keepcoder.Telegram".into(),
            ],
        },
        CleanRule {
            id: "comm_whatsapp".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "WhatsApp Cache".into(),
            paths: vec![
                "~/Library/Caches/net.whatsapp.WhatsApp".into(),
                "~/Library/Group Containers/group.net.whatsapp.WhatsApp.shared/Message/Media".into(),
            ],
        },
        CleanRule {
            id: "comm_wechat".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "WeChat Cache".into(),
            paths: vec![
                "~/Library/Caches/com.tencent.xinWeChat".into(),
                "~/Library/Application Support/com.tencent.xinWeChat".into(),
            ],
        },
        CleanRule {
            id: "comm_skype".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "Skype Cache".into(),
            paths: vec![
                "~/Library/Caches/com.skype.skype".into(),
                "~/Library/Application Support/Skype Helper".into(),
            ],
        },
        CleanRule {
            id: "comm_signal".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "Signal Cache".into(),
            paths: vec![
                "~/Library/Caches/org.whispersystems.signal-desktop".into(),
                "~/Library/Application Support/Signal/Cache".into(),
            ],
        },
        CleanRule {
            id: "comm_legcord".into(),
            max_age_days: None,
            category: "Communication".into(),
            label: "Legcord Cache".into(),
            paths: vec![
                "~/Library/Application Support/legcord/Cache".into(),
                "~/Library/Application Support/legcord/Code Cache".into(),
                "~/Library/Application Support/legcord/GPUCache".into(),
            ],
        },
        // ── AI Tools ────────────────────────────────────────
        CleanRule {
            id: "ai_chatgpt".into(),
            max_age_days: None,
            category: "AI Tools".into(),
            label: "ChatGPT Cache".into(),
            paths: vec!["~/Library/Caches/com.openai.chat".into()],
        },
        CleanRule {
            id: "ai_claude_desktop".into(),
            max_age_days: None,
            category: "AI Tools".into(),
            label: "Claude Desktop Cache".into(),
            paths: vec![
                "~/Library/Caches/com.anthropic.claudedesktop".into(),
                "~/Library/Application Support/Claude/Cache".into(),
            ],
        },
        CleanRule {
            id: "ai_cursor".into(),
            max_age_days: None,
            category: "AI Tools".into(),
            label: "Cursor Cache".into(),
            paths: vec![
                "~/Library/Caches/com.todesktop.230313mzl4w4u92".into(),
                "~/Library/Application Support/Cursor/Cache".into(),
                "~/Library/Application Support/Cursor/CachedData".into(),
            ],
        },
        CleanRule {
            id: "ai_windsurf".into(),
            max_age_days: None,
            category: "AI Tools".into(),
            label: "Windsurf Cache".into(),
            paths: vec!["~/Library/Caches/com.codeium.windsurf".into()],
        },
        // ── Design ──────────────────────────────────────────
        CleanRule {
            id: "design_figma".into(),
            max_age_days: None,
            category: "Design".into(),
            label: "Figma Cache".into(),
            paths: vec![
                "~/Library/Caches/com.figma.Desktop".into(),
                "~/Library/Application Support/Figma/Cache".into(),
            ],
        },
        CleanRule {
            id: "design_sketch".into(),
            max_age_days: None,
            category: "Design".into(),
            label: "Sketch Cache".into(),
            paths: vec!["~/Library/Caches/com.bohemiancoding.sketch3".into()],
        },
        CleanRule {
            id: "design_adobe".into(),
            max_age_days: None,
            category: "Design".into(),
            label: "Adobe Creative Cloud Cache".into(),
            paths: vec![
                "~/Library/Caches/Adobe".into(),
                "~/Library/Logs/Adobe".into(),
                "~/Library/Application Support/Adobe/Common/Media Cache".into(),
            ],
        },
        CleanRule {
            id: "design_blender".into(),
            max_age_days: None,
            category: "Design".into(),
            label: "Blender Cache".into(),
            paths: vec!["~/Library/Caches/org.blenderfoundation.blender".into()],
        },
        // ── Media & Audio ───────────────────────────────────
        CleanRule {
            id: "media_spotify".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "Spotify Cache".into(),
            paths: vec![
                "~/Library/Caches/com.spotify.client".into(),
                "~/Library/Application Support/Spotify/PersistentCache".into(),
            ],
        },
        CleanRule {
            id: "media_final_cut".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "Final Cut Pro Cache".into(),
            paths: vec![
                "~/Library/Caches/com.apple.FinalCut".into(),
                "~/Movies/Motion Templates.localized".into(),
            ],
        },
        CleanRule {
            id: "media_davinci_resolve".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "DaVinci Resolve Cache".into(),
            paths: vec![
                "~/Library/Application Support/Blackmagic Design/DaVinci Resolve/Cache".into(),
            ],
        },
        CleanRule {
            id: "media_obs".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "OBS Cache & Logs".into(),
            paths: vec![
                "~/Library/Application Support/obs-studio/logs".into(),
                "~/Library/Caches/com.obsproject.obs-studio".into(),
            ],
        },
        CleanRule {
            id: "media_iina".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "IINA Cache".into(),
            paths: vec!["~/Library/Caches/com.colliderli.iina".into()],
        },
        CleanRule {
            id: "media_vlc".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "VLC Cache".into(),
            paths: vec!["~/Library/Caches/org.videolan.vlc".into()],
        },
        CleanRule {
            id: "media_handbrake".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "HandBrake Logs".into(),
            paths: vec![
                "~/Library/Application Support/HandBrake/EncodeLogs".into(),
            ],
        },
        CleanRule {
            id: "media_apple_music".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "Apple Music Cache".into(),
            paths: vec!["~/Library/Caches/com.apple.Music".into()],
        },
        CleanRule {
            id: "media_apple_tv".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "Apple TV Cache".into(),
            paths: vec!["~/Library/Caches/com.apple.TV".into()],
        },
        CleanRule {
            id: "media_plex".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "Plex Cache".into(),
            paths: vec!["~/Library/Caches/tv.plex.player.desktop".into()],
        },
        CleanRule {
            id: "media_mpv".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "MPV Cache".into(),
            paths: vec!["~/Library/Caches/io.mpv".into()],
        },
        CleanRule {
            id: "media_podcasts".into(),
            max_age_days: None,
            category: "Media & Audio".into(),
            label: "Podcasts Cache".into(),
            paths: vec!["~/Library/Caches/com.apple.podcasts".into()],
        },
        // ── Notes & Productivity ────────────────────────────
        CleanRule {
            id: "notes_notion".into(),
            max_age_days: None,
            category: "Notes & Productivity".into(),
            label: "Notion Cache".into(),
            paths: vec![
                "~/Library/Caches/notion.id".into(),
                "~/Library/Application Support/Notion/Cache".into(),
            ],
        },
        CleanRule {
            id: "notes_obsidian".into(),
            max_age_days: None,
            category: "Notes & Productivity".into(),
            label: "Obsidian Cache".into(),
            paths: vec!["~/Library/Caches/md.obsidian".into()],
        },
        CleanRule {
            id: "notes_bear".into(),
            max_age_days: None,
            category: "Notes & Productivity".into(),
            label: "Bear Cache".into(),
            paths: vec!["~/Library/Caches/net.shinyfrog.bear".into()],
        },
        CleanRule {
            id: "notes_evernote".into(),
            max_age_days: None,
            category: "Notes & Productivity".into(),
            label: "Evernote Cache".into(),
            paths: vec!["~/Library/Caches/com.evernote.Evernote".into()],
        },
        CleanRule {
            id: "notes_todoist".into(),
            max_age_days: None,
            category: "Notes & Productivity".into(),
            label: "Todoist Cache".into(),
            paths: vec!["~/Library/Caches/com.todoist.mac.Todoist".into()],
        },
        CleanRule {
            id: "notes_linear".into(),
            max_age_days: None,
            category: "Notes & Productivity".into(),
            label: "Linear Cache".into(),
            paths: vec!["~/Library/Caches/com.linear".into()],
        },
        CleanRule {
            id: "notes_raindrop".into(),
            max_age_days: None,
            category: "Notes & Productivity".into(),
            label: "Raindrop Cache".into(),
            paths: vec!["~/Library/Caches/io.raindrop.macapp".into()],
        },
        CleanRule {
            id: "notes_logseq".into(),
            max_age_days: None,
            category: "Notes & Productivity".into(),
            label: "Logseq Cache".into(),
            paths: vec!["~/Library/Caches/com.electron.logseq".into()],
        },
        // ── Utilities ───────────────────────────────────────
        CleanRule {
            id: "util_alfred".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "Alfred Cache".into(),
            paths: vec![
                "~/Library/Caches/com.runningwithcrayons.Alfred".into(),
            ],
        },
        CleanRule {
            id: "util_raycast".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "Raycast Cache".into(),
            paths: vec!["~/Library/Caches/com.raycast.macos".into()],
        },
        CleanRule {
            id: "util_1password".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "1Password Cache".into(),
            paths: vec!["~/Library/Caches/com.1password.1password".into()],
        },
        CleanRule {
            id: "util_cleanshot".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "CleanShot Cache".into(),
            paths: vec!["~/Library/Caches/com.cleanshot.app".into()],
        },
        CleanRule {
            id: "util_unarchiver".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "The Unarchiver Cache".into(),
            paths: vec![
                "~/Library/Caches/com.macpaw.site.theunarchiver".into(),
            ],
        },
        CleanRule {
            id: "util_homebrew".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "Homebrew Cache".into(),
            paths: vec!["~/Library/Caches/Homebrew".into()],
        },
        CleanRule {
            id: "util_teamviewer".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "TeamViewer Cache & Logs".into(),
            paths: vec![
                "~/Library/Caches/com.teamviewer.TeamViewer".into(),
                "~/Library/Logs/TeamViewer".into(),
            ],
        },
        CleanRule {
            id: "util_anydesk".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "AnyDesk Logs".into(),
            paths: vec!["~/Library/Logs/AnyDesk".into()],
        },
        CleanRule {
            id: "util_todesk".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "ToDesk Cache".into(),
            paths: vec!["~/Library/Caches/com.todesk.desktop".into()],
        },
        // ── Gaming ──────────────────────────────────────────
        CleanRule {
            id: "game_steam".into(),
            max_age_days: None,
            category: "Gaming".into(),
            label: "Steam Cache & Logs".into(),
            paths: vec![
                "~/Library/Application Support/Steam/appcache".into(),
                "~/Library/Application Support/Steam/htmlcache".into(),
                "~/Library/Application Support/Steam/depotcache".into(),
                "~/Library/Application Support/Steam/logs".into(),
            ],
        },
        CleanRule {
            id: "game_epic".into(),
            max_age_days: None,
            category: "Gaming".into(),
            label: "Epic Games Cache".into(),
            paths: vec![
                "~/Library/Caches/com.epicgames.EpicGamesLauncher".into(),
            ],
        },
        CleanRule {
            id: "game_minecraft".into(),
            max_age_days: None,
            category: "Gaming".into(),
            label: "Minecraft Logs & Crash Reports".into(),
            paths: vec![
                "~/Library/Application Support/minecraft/logs".into(),
                "~/Library/Application Support/minecraft/crash-reports".into(),
            ],
        },
        CleanRule {
            id: "game_steam_shaders".into(),
            max_age_days: None,
            category: "Gaming".into(),
            label: "Steam Shader Cache".into(),
            paths: vec![
                "~/Library/Application Support/Steam/steamapps/shadercache".into(),
                "~/Library/Caches/com.valvesoftware.steam".into(),
            ],
        },
        CleanRule {
            id: "game_battle_net".into(),
            max_age_days: None,
            category: "Gaming".into(),
            label: "Battle.net Cache".into(),
            paths: vec![
                "~/Library/Application Support/Battle.net/Cache".into(),
                "~/Library/Caches/com.blizzard.Battle.net".into(),
            ],
        },
        CleanRule {
            id: "game_minecraft_extra".into(),
            max_age_days: None,
            category: "Gaming".into(),
            label: "Minecraft Web Cache".into(),
            paths: vec![
                "~/Library/Application Support/minecraft/webcache".into(),
                "~/Library/Application Support/minecraft/webcache2".into(),
            ],
        },
        // ── Downloads & Torrents ────────────────────────────
        CleanRule {
            id: "torrent_transmission".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "Transmission Cache".into(),
            paths: vec!["~/Library/Caches/org.m0k.transmission".into()],
        },
        CleanRule {
            id: "torrent_qbittorrent".into(),
            max_age_days: None,
            category: "Utilities".into(),
            label: "qBittorrent Cache".into(),
            paths: vec!["~/Library/Caches/qBittorrent".into()],
        },
        // ── Email ──────────────────────────────────────────
        CleanRule {
            id: "email_spark".into(),
            max_age_days: None,
            category: "Email".into(),
            label: "Spark Cache".into(),
            paths: vec!["~/Library/Caches/com.readdle.smartemail-Mac".into()],
        },
        CleanRule {
            id: "email_airmail".into(),
            max_age_days: None,
            category: "Email".into(),
            label: "Airmail Cache".into(),
            paths: vec!["~/Library/Caches/com.airmail.Airmail3".into()],
        },
        // ── Saved State ─────────────────────────────────────
        CleanRule {
            id: "saved_app_state".into(),
            max_age_days: Some(30),
            category: "Saved State".into(),
            label: "Saved Application State".into(),
            paths: vec!["~/Library/Saved Application State".into()],
        },
    ]
}
